export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_ERROR = 'FETCH_CHARACTERS_ERROR';
export const RESET_CHARACTERS_LIST = 'RESET_CHARACTERS_LIST';
export const FETCH_CHARACTER_DETAIL_SUCCESS = 'FETCH_CHARACTER_DETAIL_SUCCESS';
export const FETCH_CHARACTER_DETAIL_ERROR = 'FETCH_CHARACTER_DETAIL_ERROR';
export const RESET_CHARACTER_DETAIL = 'RESET_CHARACTER_DETAIL';
export const SET_FAVOURITE_CHARACTER_SUCCESS = 'SET_FAVOURITE_CHARACTER_SUCCESS';
export const SET_FAVOURITE_CHARACTER_ERROR = 'SET_FAVOURITE_CHARACTER_ERROR';
